// Services data for dynamic loading

const servicesData = {
    'gym': {
        id: 'gym',
        title: 'Тренажёрный зал',
        badge: 'Фитнес',
        price: '100-200р',
        image: 'Card_Service_Image.png',
        galleryImage: 'Image_peredel.png',
        description: 'Тренажёрный зал оснащён оборудованием для силовых и общефизических занятий. Здесь можно заниматься самостоятельно или под наблюдением тренера, соблюдая комфортную нагрузку и технику выполнения упражнений.',
        duration: '1 час',
        format: 'Групповое',
        age: 'от 14 лет',
        level: 'Любой'
    },
    'shaping': {
        id: 'shaping',
        title: 'Шейпинг',
        badge: 'Групповые',
        price: '100-250р',
        image: 'Card_Service_Image_2.png',
        galleryImage: 'Card_Service_Image_2.png',
        description: 'Групповые занятия шейпингом для улучшения фигуры и общего тонуса организма. Программа включает комплекс упражнений для всех групп мышц.',
        duration: '1 час',
        format: 'Групповое',
        age: 'от 16 лет',
        level: 'Любой'
    },
    'yoga': {
        id: 'yoga',
        title: 'Йога',
        badge: 'Групповые',
        price: '125-250р',
        image: 'Card_Service_Image_3.png',
        galleryImage: 'Card_Service_Image_3.png',
        description: 'Занятия йогой для развития гибкости, силы и внутренней гармонии. Подходит для всех уровней подготовки.',
        duration: '1 час',
        format: 'Групповое',
        age: 'от 12 лет',
        level: 'Любой'
    },
    'aerobics': {
        id: 'aerobics',
        title: 'Аэробика',
        badge: 'Групповые',
        price: '125-250р/час',
        image: 'Card_Service_Image_4.png',
        galleryImage: 'Card_Service_Image_4.png',
        description: 'Динамичные групповые занятия аэробикой для улучшения сердечно-сосудистой системы и выносливости.',
        duration: '1 час',
        format: 'Групповое',
        age: 'от 14 лет',
        level: 'Любой'
    },
    'horse-riding': {
        id: 'horse-riding',
        title: 'Верховая езда на лошадях',
        badge: 'Спорт',
        price: '100-200р/час',
        image: 'Card_Service_Image_5.png',
        galleryImage: 'Card_Service_Image_5.png',
        description: 'Верховая езда для всех желающих. Опытные инструкторы помогут освоить основы верховой езды.',
        duration: '1 час',
        format: 'Индивидуальное',
        age: 'от 8 лет',
        level: 'Любой'
    },
    'horse-training': {
        id: 'horse-training',
        title: 'Обучение верховой езде',
        badge: 'Спорт',
        price: '700р/ час',
        image: 'Card_Service_Image_6.png',
        galleryImage: 'Card_Service_Image_6.png',
        description: 'Профессиональное обучение верховой езде с индивидуальным подходом. Подходит для начинающих и продвинутых всадников.',
        duration: '1 час',
        format: 'Индивидуальное',
        age: 'от 8 лет',
        level: 'Любой'
    },
    'walking-poles': {
        id: 'walking-poles',
        title: 'Прокат палок для ходьбы',
        badge: 'Прокат',
        price: '100р/час',
        image: 'Card_Service_Image_7.png',
        galleryImage: 'Card_Service_Image_7.png',
        description: 'Прокат палок для скандинавской ходьбы. Идеально для активного отдыха и тренировок на свежем воздухе.',
        duration: '1 час',
        format: 'Прокат',
        age: 'без ограничений',
        level: 'Любой'
    },
    'rollers': {
        id: 'rollers',
        title: 'Прокат роликов',
        badge: 'Прокат',
        price: '150р/час',
        image: 'Card_Service_Image_8.png',
        galleryImage: 'Card_Service_Image_8.png',
        description: 'Прокат роликовых коньков различных размеров. Отличный способ провести время активно и весело.',
        duration: '1 час',
        format: 'Прокат',
        age: 'от 6 лет',
        level: 'Любой'
    },
    'skis': {
        id: 'skis',
        title: 'Прокат лыж',
        badge: 'Прокат',
        price: '100р/час',
        image: 'Card_Service_Image_9.png',
        galleryImage: 'Card_Service_Image_9.png',
        description: 'Прокат лыжного инвентаря для любителей зимних видов спорта. Различные размеры и типы лыж.',
        duration: '1 час',
        format: 'Прокат',
        age: 'от 6 лет',
        level: 'Любой'
    },
    'tennis': {
        id: 'tennis',
        title: 'Теннисный корт',
        badge: 'Спорт',
        price: '200-300р/час',
        image: 'Card_Service_Image_10.png',
        galleryImage: 'Card_Service_Image_10.png',
        description: 'Аренда теннисного корта для игры в большой теннис. Профессиональное покрытие и все необходимое оборудование.',
        duration: '1 час',
        format: 'Индивидуальное',
        age: 'от 8 лет',
        level: 'Любой'
    },
    'sauna': {
        id: 'sauna',
        title: 'Сауна с бассейном',
        badge: 'Здоровье',
        price: '1800р/час',
        image: 'Card_Service_Image_11.png',
        galleryImage: 'Card_Service_Image_11.png',
        description: 'Комплекс сауны с бассейном для релаксации и восстановления. Идеальное место для отдыха после тренировок.',
        duration: '1 час',
        format: 'Групповое',
        age: 'от 16 лет',
        level: 'Любой'
    },
    'press-center': {
        id: 'press-center',
        title: 'Пресс-центр',
        badge: 'Фитнес',
        price: '1200р/час',
        image: 'Card_Service_Image_12.png',
        galleryImage: 'Card_Service_Image_12.png',
        description: 'Современный пресс-центр с профессиональным оборудованием для силовых тренировок и функционального тренинга.',
        duration: '1 час',
        format: 'Групповое',
        age: 'от 14 лет',
        level: 'Любой'
    },
    'billiards': {
        id: 'billiards',
        title: 'Услуги бильярда',
        badge: 'Досуг',
        price: '200р/час',
        image: 'Card_Service_Image_13.png',
        galleryImage: 'Card_Service_Image_13.png',
        description: 'Игровые столы для бильярда. Отличное место для проведения досуга с друзьями и семьей.',
        duration: '1 час',
        format: 'Групповое',
        age: 'от 12 лет',
        level: 'Любой'
    }
};

